MODEL:
  META_ARCHITECTURE: "SparseRCNN"
  PIXEL_MEAN: [113.3451167, 113.3451167, 113.3451167]
  PIXEL_STD: [61.77659969, 61.77659969, 61.77659969]
  DEVICE: "cuda"
  WEIGHTS: "/content/drive/MyDrive/dentex/quadrant_output/best_model"
  BACKBONE:
    NAME: "FeatureExtractor"
  ROI_HEADS:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
  ROI_BOX_HEAD:
    POOLER_TYPE: "ROIAlignV2"
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
  SparseRCNN:
    NUM_PROPOSALS: 100
    NUM_CLASSES: (8,)
    MULTI_HEAD_TRAIN: (True,)
SOLVER:
  BASE_LR: 0.000025
  IMS_PER_BATCH: 2
  STEPS: []
  MAX_ITER: 31150                # num_epochs * steps_per_epoch
  CHECKPOINT_PERIOD: 3210        # each 10 epochs
  # IMS_PER_BATCH: 2
  # BASE_LR: 0.001
  # STEPS: (210000, 250000)
  # MAX_ITER: 270000
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 1000
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 1.0  # keep same with BASE_LR.
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 1.0
    NORM_TYPE: 2.0
SEED: 40244023
INPUT:
  MIN_SIZE_TRAIN: (448,)
  MAX_SIZE_TRAIN: 448
  MIN_SIZE_TEST: 448
  MAX_SIZE_TEST: 448
  CROP:
    ENABLED: False
    TYPE: "absolute_range"
    SIZE: (384, 600)
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 312
  # EVAL_PERIOD: 100
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 2
DATASETS:
  TRAIN: ("Enumeration_train",) # 623 images --> 312 steps per epochs for batch_size 2
  TEST:  ("Enumeration_val",) # 70 images
VERSION: 2
OUTPUT_DIR: "/content/drive/MyDrive/dentex/enumeration_outputs"