_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  DEVICE: "cuda"
  PIXEL_MEAN: [113.3451167, 113.3451167, 113.3451167]
  PIXEL_STD: [61.77659969, 61.77659969, 61.77659969]
  WEIGHTS: "/content/drive/MyDrive/dentex/quadrant_output/best_model"
  SparseRCNN:
    NUM_PROPOSALS: 4
    NUM_CLASSES: 4
DATASETS:
  TRAIN: ("Quadrant_train",) # 623 images --> 312 steps per epochs for batch_size 2
  TEST:  ("Quadrant_val",) # 70 images
DATALOADER:
  NUM_WORKERS: 2
SOLVER:
  BASE_LR: 0.001
  IMS_PER_BATCH: 2
  STEPS: []
  MAX_ITER: 31150                # num_epochs * steps_per_epoch
  CHECKPOINT_PERIOD: 3210        # each 10 epochs
TEST:
  EVAL_PERIOD: 312
INPUT:
  MIN_SIZE_TRAIN: (448,)
  MAX_SIZE_TRAIN: 448
  MIN_SIZE_TEST: 448
  MAX_SIZE_TEST: 448
  CROP:
    ENABLED: False
  FORMAT: "RGB"
OUTPUT_DIR: "/content/drive/MyDrive/dentex/quadrant_outputs"